INSERT INTO `dpa`.`area` (`id`, `nombre`, `sigla`, `descripcion`, `estado`) 
VALUES ('1', 'Logica', 'AL', NULL, 'ac'), 
	   ('2', 'Matematicas', 'LD', NULL, 'AC'),
	   ('3', 'Astronomia y Astrofisica', 'LD', NULL, 'AC'),
	   ('4', 'Fisica', 'LD', NULL, 'AC'),
	   ('5', 'Quimica', 'LD', NULL, 'AC'),
	   ('6', 'Ciencias De La Vida', 'LD', NULL, 'AC'),
	   ('7', 'Ciencias De La Tierra y el Espacio', 'LD', NULL, 'AC'),
	   ('8', 'Ciencias Agrarias', 'LD', NULL, 'AC'),
	   ('9', 'Ciencas Medicas', 'LD', NULL, 'AC'),
	   ('10', 'Ciencias Tegnologicas', 'LD', NULL, 'AC'),
	   ('11', 'Antropologia', 'LD', NULL, 'AC'),
	   ('12', 'Demografia', 'LD', NULL, 'AC'),
	   ('13', 'Ciencias Economicas', 'LD', NULL, 'AC'),
	   ('14', 'Geografia', 'LD', NULL, 'AC'),
	   ('15', 'Historia', 'LD', NULL, 'AC'),
	   ('16', 'Ciencias Juridicas y Derecho', 'LD', NULL, 'AC'),
	   ('17', 'Linguistica', 'LD', NULL, 'AC'),	   
	   ('18', 'Pedagogia', 'LD', NULL, 'AC'),
	   ('19', 'Ciencia Politica', 'LD', NULL, 'AC'),
	   ('20', 'Psicologia', 'LD', NULL, 'AC'),
	   ('21', 'Ciencias De Las Artes y Las Letras', 'LD', NULL, 'AC'),
	   ('22', 'Sociologia', 'LD', NULL, 'AC'),
	   ('23', 'Etica', 'LD', NULL, 'AC'),
	   ('24', 'Filosofia', 'LD', NULL, 'AC');
	   
