INSERT INTO `dpa`.`subarea` (`id`, `nombre_subarea`, `sigla_subarea`, `area_id`, `estado`) 
VALUES ('1', 'Aplicaciones de la lógica', 'AL', '1', 'ac'),
	   ('2', 'Lógica deductiva', 'LD', '1', 'ac'),
	   ('3', 'Lógica general', 'LD', '1', 'ac'),
	   ('4', 'Lógica inductiva', 'LD', '1', 'ac'),
	   ('5', 'Metodologia', 'LD', '1', 'ac'),
	   ('6', 'Otras especialidades relativas a la lógica (especificar)', 'LD', '1', 'ac'),
	   ('7', 'Algebra', 'LD', '2', 'ac'),
	   ('8', 'Análisis y análisis funcicnal', 'LD', '2', 'ac'),
	   ('9', 'Ciencia de los ordenadores ', 'LD', '2', 'ac'),
	   ('10', 'Geometría', 'LD', '23', 'ac'),
	   ('11', 'Teoría de números ', 'LD', '2', 'ac'),
	   ('12', 'Análisis numérico', 'LD', '2', 'ac'),
	   ('13', 'Investigación operativa', 'LD', '2', 'ac'),
	   ('14', 'Probabilidad', 'LD', '2', 'ac'),
	   ('15', 'Estadística', 'LD', '2', 'ac'),
	   ('16', 'Topología', 'LD', '2', 'ac'),
	   ('17', 'Otras especialidades matemáticas (especificar)', 'LD', '2', 'ac'),
	   ('18', 'Cosmología y cosmogonía', 'LD', '3', 'ac'),
	   ('19', 'Medio interplanetario', 'LD', '3', 'ac'),
	   ('20', 'Astronomía óptica', 'LD', '3', 'ac'),
	   ('21', 'Planetología', 'LD', '3', 'ac'),
	   ('22', 'Radioastronomía', 'LD', '3', 'ac'),
	   ('23', 'Sistema solar', 'LD', '3', 'ac'),
	   ('24', 'Otras especialidades astronómicas (especificar)', 'LD', '3', 'ac'),
	   ('25', 'Acústica', 'LD', '4', 'ac'),
	   ('26', 'Electromagnetismo', 'LD', '4', 'ac'),
	   ('27', 'Electrónica', 'LD', '4', 'ac'),
	   ('28', 'Física de los fluidos', 'LD', '4', 'ac'),
	   ('29', 'Mecánica', 'LD', '4', 'ac'),
	   ('30', 'Física molecular', 'LD', '4', 'ac'),
	   ('31', 'Física atómica y nuclear ', 'LD', '4', 'ac'),
	   ('32', 'Nucleónica', 'LD', '4', 'ac'),
	   ('33', 'Optica', 'LD', '4', 'ac'),
	   ('34', 'Química física', 'LD', '4', 'ac'),
	   ('35', 'Física del estado sólido', 'LD', '4', 'ac'),
	   ('36', 'Física teórica', 'LD', '4', 'ac'),
	   ('37', 'Termodinámica', 'LD', '4', 'ac'),
	   ('38', 'Unidades y constantes', 'LD', '4', 'ac'),
	   ('39', 'Fisica Altas Energías', 'LD', '4', 'ac'),
	   ('40', 'Otras especialidades físicas (especificar)', 'LD', '4', 'ac'),
	   ('41', 'Química analítica', 'LD', '5', 'ac'),
	   ('42', 'Bioquímica', 'LD', '5', 'ac')
	   ('43', 'Química inorgánica', 'LD', '5', 'ac')
	   ('44', 'Química macromolecular', 'LD', '5', 'ac')
	   ('45', 'Química nuclear', 'LD', '5', 'ac')
	   ('46', 'Química orgánica', 'LD', '5', 'ac')
	   ('47', 'Química física ', 'LD', '5', 'ac')
	   ('48', 'Química Farmacéutica', 'LD', '5', 'ac')
	   ('49', 'Química ambiental', 'LD', '5', 'ac')
	   ('50', 'Otras especialidades (especificar)', 'LD', '5', 'ac')
	   ('51', ' Biología animal (Zoología)', 'LD', '6', 'ac')
	   ('52', 'Antropología (Física)', 'LD', '6', 'ac')
	   ('53', 'Antropología (Física)', 'LD', '6', 'ac')
	   ('54', 'Biomatemáticas', 'LD', '6', 'ac')
	   ('55', 'Biometría', 'LD', '6', 'ac')
	   ('56', 'Biofísica', 'LD', '6', 'ac')
	   ('57', 'Biología celular', 'LD', '6', 'ac')
	   ('58', 'Etología', 'LD', '6', 'ac')
	   ('59', 'Genética', 'LD', '6', 'ac')
	   ('60', 'Biología humana ', 'LD', '6', 'ac')
	   ('61', 'Fisiología humana', 'LD', '6', 'ac')
	   ('62', 'Inmunología', 'LD', '6', 'ac')
	   ('63', 'Biología de insectos (Entomología) ', 'LD', '6', 'ac')
	   ('64', 'Microbiología', 'LD', '6', 'ac')
	   ('65', 'Biología molecular', 'LD', '6', 'ac')
	   ('66', 'Paleontología', 'LD', '6', 'ac')
	   ('67', 'Biología Vegetal (Botánica)', 'LD', '6', 'ac')
	   ('68', 'Radiobiología', 'LD', '6', 'ac')
	   ('69', 'Simbiosis', 'LD', '6', 'ac')
	   ('70', 'Virología', 'LD', '6', 'ac')
	   ('71', 'Neurociencias', 'LD', '6', 'ac')
	   ('72', 'Otras especialidades biológicas (especificar )', 'LD', '6', 'ac')
	   ('73', 'Clencias de la atmósfera ', 'LD', '7', 'ac'),
	   ('74', 'Climatología', 'LD', '7', 'ac'),
	   ('75', 'Geoquímica', 'LD', '7', 'ac'),
	   ('76', 'Geodesla', 'LD', '7', 'ac'),
	   ('77', 'Geografía', 'LD', '7', 'ac'),
	   ('78', 'Geología', 'LD', '7', 'ac'),
	   ('79', 'Geofísica', 'LD', '7', 'ac'),
	   ('80', 'Hidrologia', 'LD', '7', 'ac'),
	   ('81', 'Meteorologia', 'LD', '7', 'ac'),
	   ('82', 'Oceanografia', 'LD', '7', 'ac'),
	   ('83', 'Ciencias del suelo (Edafología)', 'LD', '7', 'ac'),
	   ('84', 'Ciencias del espacio', 'LD', '7', 'ac'),
	   ('85', 'Otras especialidades de la tierra, espacio o entorno', 'LD', '7', 'ac'),
	   ('86', 'Agroquímica', 'LD', '8', 'ac'),
	   ('87', 'Ingeniería Agrícola', 'LD', '8', 'ac'),
	   ('88', 'Agronomía', 'LD', '8', 'ac'),
	   ('89', 'Producción animal', 'LD', '8', 'ac'),
	   ('90', 'Peces y fauna silvestre', 'LD', '8', 'ac'),
	   ('91', 'Ciencia forestal', 'LD', '8', 'ac'),
	   ('92', 'Horticultura', 'LD', '8', 'ac'),
	   ('93', 'Fitopatología', 'LD', '8', 'ac'),
	   ('94', 'Ciencias veterinarias ', 'LD', '8', 'ac'),
	   ('95', 'Otras especialidades agrarias (especificar)', 'LD', '8', 'ac'),
	   ('96', 'Ciencias clínicas', 'LD', '9', 'ac'),
	   ('97', 'Epidemología', 'LD', '9', 'ac'),
	   ('98', 'Medicina Forense ', 'LD', '9', 'ac'),
	   ('99', 'Medicina del trabajo', 'LD', '9', 'ac'),
	   ('100', 'Medicina interna', 'LD', '9', 'ac'),
	   ('101', 'Ciencias de la Nutrición', 'LD', '9', 'ac'),
	   ('102', 'Patología', 'LD', '9', 'ac'),
	   ('103', 'Farmacodinámica', 'LD', '9', 'ac'),
	   ('104', 'Farmacología', 'LD', '9', 'ac'),
	   ('105', 'Medicina preventiva', 'LD', '9', 'ac'),
	   ('106', 'Psiquiatría', 'LD', '9', 'ac'),
	   ('107', 'Salud pública', 'LD', '9', 'ac'),
	   ('108', 'Cirugía', 'LD', '9', 'ac'),
	   ('109', 'Toxicología', 'LD', '9', 'ac'),
	   ('110', 'Otras especialidades médicas (especificar)', 'LD', '9', 'ac'),
	   ('111', 'Ingeniería y tecnología aeronáuticas', 'LD', '10', 'ac'),
	   ('112', 'Tecnología bioquímica', 'LD', '10', 'ac'),
	   ('113', 'Ingeniería y tecnología químicas', 'LD', '10', 'ac'),
	   ('114', 'Tecnologla de los ordenadores', 'LD', '10', 'ac'),
	   ('115', 'Tecnología de la construcion', 'LD', '10', 'ac'),
	   ('116', 'Ingeniería y tecnología eléctricas', 'LD', '10', 'ac'),
	   ('117', 'Tecnología electrónica', 'LD', '10', 'ac'),
	   ('118', 'Ingeniería y tecnología del medio ambiente', 'LD', '10', 'ac'),
	   ('119', 'Tecnología de los alimentos ', 'LD', '10', 'ac'),
	   ('120', 'Tecnología industrial', 'LD', '10', 'ac'),
	   ('121', 'Tecnología de la instrumentación', 'LD', '10', 'ac'),
	   ('122', 'Tecnología de materiales', 'LD', '10', 'ac'),
	   ('123', 'Tecnología e ingeniería mecánicas', 'LD', '10', 'ac'),
	   ('124', 'Tecnología médica ', 'LD', '10', 'ac'),
	   ('125', 'Tecnología metalúrgica', 'LD', '10', 'ac'),
	   ('126', 'Tecnología de productos metálicos', 'LD', '10', 'ac'),
	   ('127', 'Tecnología de vehículos de motor', 'LD', '10', 'ac'),
	   ('128', 'Tecnología minera', 'LD', '10', 'ac'),
	   ('129', 'Tecnología naval', 'LD', '10', 'ac'),
	   ('130', 'Tecnología nuclear', 'LD', '10', 'ac'),
	   ('131', 'Tecnología del carbón y del petróleo', 'LD', '10', 'ac'),
	   ('132', 'Tecnología energética', 'LD', '10', 'ac'),
	   ('133', 'Tecnología de los ferrocarriles', 'LD', '10', 'ac'),
	   ('134', 'Tecnología del espacio', 'LD', '10', 'ac'),
	   ('135', 'Tecnología de las telecomunicaciones', 'LD', '10', 'ac'),
	   ('136', 'Tecnología textil ', 'LD', '10', 'ac'),
	   ('137', 'Tecnología de los sistemas de transporte', 'LD', '10', 'ac'),
	   ('138', 'Procesos tecnológicos', 'LD', '10', 'ac'),
	   ('139', 'Planificación urbana', 'LD', '10', 'ac'),
	   ('140', 'Otras especialidades tecnológicas (especificar)', 'LD', '10', 'ac'),
	   ('141', 'Antropología cultural', 'LD', '11', 'ac'),
	   ('142', 'Etnografía y etnología', 'LD', '11', 'ac'),
	   ('143', 'Antropología social', 'LD', '11', 'ac'),
	   ('144', 'Otras especialidades (especificar)', 'LD', '11', 'ac'),
	   ('145', 'Fertilidad', 'LD', '12', 'ac'),
	   ('146', 'Demografía general', 'LD', '12', 'ac'),
	   ('147', 'Demografía geográfica', 'LD', '12', 'ac'),
	   ('148', 'Demografía histórica', 'LD', '12', 'ac'),
	   ('149', 'Mortalidad', 'LD', '12', 'ac'),
	   ('150', 'Características de la población', 'LD', '12', 'ac'),
	   ('151', 'Tamaño de la población y evolución demográfica', 'LD', '12', 'ac'),
	   ('152', 'Otras especialidades demograficas (especificar)', 'LD', '12', 'ac'),
	   ('153', 'Política fiscal y hacienda públlca nacionales', 'LD', '13', 'ac'),
	   ('154', 'Econometría', 'LD', '13', 'ac'),
	   ('155', 'Contabilidad económica', 'LD', '13', 'ac'),
	   ('156', 'Actividad económica', 'LD', '13', 'ac'),
	   ('157', 'Sistemas económicos', 'LD', '13', 'ac'),
	   ('158', 'Economía del cambio tecnológico', 'LD', '13', 'ac'),
	   ('159', 'Teoría económica', 'LD', '13', 'ac'),
	   ('160', 'Economía general', 'LD', '13', 'ac'),
	   ('161', 'Organización industrial y politicas gubernamentales', 'LD', '13', 'ac'),
	   ('162', 'Economía internacional tecnología', 'LD', '13', 'ac'),
	   ('163', 'Organización y dirección de empresas', 'LD', '13', 'ac'),
	   ('164', 'Economía sectorial', 'LD', '13', 'ac'),
	   ('165', 'Otras especialidades económicas (especificar)', 'LD', '13', 'ac'),
	   ('166', 'Geografía económica', 'LD', '14', 'ac'),
	   ('167', 'Geografía histórica', 'LD', '14', 'ac'),
	   ('168', 'Geografía humana', 'LD', '14', 'ac'),
	   ('169', 'Geografía regional', 'LD', '14', 'ac'),
	   ('170', 'Otras especialidades geográficas (especificar)', 'LD', '14', 'ac'),
	   ('171', 'Biografías', 'LD', '15', 'ac'),
	   ('172', 'Historia general', 'LD', '15', 'ac'),
	   ('173', 'Historia de países', 'LD', '15', 'ac'),
	   ('174', 'Historia por épocas', 'LD', '15', 'ac'),
	   ('175', 'Ciencias auxiliares de la historia', 'LD', '15', 'ac'),
	   ('176', 'Historia por especialidades', 'LD', '15', 'ac'),
	   ('177', 'Otras especialidades históricas (especificar)', 'LD', '15', 'ac'),
	   ('178', 'Derecho canónico', 'LD', '16', 'ac'),
	   ('179', 'Teoría y métodos generales', 'LD', '16', 'ac'),
	   ('180', 'Derecho internacional', 'LD', '16', 'ac'),
	   ('181', 'Organización jurídica', 'LD', '16', 'ac'),
	   ('182', 'Derecho y legislación nacionales', 'LD', '16', 'ac'),
	   ('183', 'Otras especialidades jurídicas (especificar)', 'LD', '16', 'ac'),
	   ('184', 'Linguística aplicada', 'LD', '17', 'ac'),
	   ('185', 'Linguística diacrónica', 'LD', '17', 'ac'),
	   ('186', 'Geografia linguística', 'LD', '17', 'ac'),
	   ('187', 'Teoria linguística', 'LD', '17', 'ac'),
	   ('188', 'Linguística sincrónica', 'LD', '17', 'ac'),
	   ('189', 'Otras especialidades linguísticas (especificar)', 'LD', '17', 'ac'),
	   ('190', 'Teoria y métodos educativos', 'LD', '18', 'ac'),
	   ('191', 'Organización y planificación', 'LD', '18', 'ac'),
	   ('192', 'Preparación y empleo de profesores', 'LD', '18', 'ac'),
	   ('193', 'Otras especialidades pedagógicas (especificar)', 'LD', '18', 'ac'),
	   ('194', 'Relaciones internacionales', 'LD', '19', 'ac'),
	   ('195', 'Ciencias políticas', 'LD', '19', 'ac'),
	   ('196', 'Ideologías políticas', 'LD', '19', 'ac'),
	   ('197', 'Vida política', 'LD', '19', 'ac'),
	   ('198', 'Sociología política', 'LD', '19', 'ac'),
	   ('199', 'Sistemas políticos', 'LD', '19', 'ac'),
	   ('200', 'Teoría política', 'LD', '19', 'ac'),
	   ('201', 'Administración pública', 'LD', '19', 'ac'),
	   ('202', 'Opinión pública', 'LD', '19', 'ac'),
	   ('203', 'Otras especialidades políticas (especificar)', 'LD', '19', 'ac'),
	   ('204', 'Patología', 'LD', '20', 'ac'),
	   ('205', 'Psicología del niño y del adolescente', 'LD', '20', 'ac'),
	   ('206', 'Asesoramiento y orientación', 'LD', '20', 'ac'),
	   ('207', 'Psicopedagogía', 'LD', '20', 'ac'),
	   ('208', 'Evaluación y diagnóstico en psicología', 'LD', '20', 'ac'),
	   ('209', 'Psicología experimental', 'LD', '20', 'ac'),
	   ('210', 'Psicología general', 'LD', '20', 'ac'),
	   ('211', 'Psicología de la vejez', 'LD', '20', 'ac'),
	   ('212', 'Psicología industrial', 'LD', '20', 'ac'),
	   ('213', 'Parapsicología', 'LD', '20', 'ac'),
	   ('214', 'Personalidad', 'LD', '20', 'ac'),
	   ('215', 'Estudio psicológico detemas sociales', 'LD', '20', 'ac'),
	   ('216', 'Psicofarmacologia', 'LD', '20', 'ac'),
	   ('217', 'Psicologia social', 'LD', '20', 'ac'),
	   ('218', 'Otras especialidades psicológicas (especificar)', 'LD', '20', 'ac'),
	   ('219', 'Arquitectura', 'LD', '21', 'ac'),
	   ('220', 'Teoría, análisis y crítica literarias', 'LD', '21', 'ac'),
	   ('221', 'Teoria, análisis y critica de las Bellas Artes', 'LD', '21', 'ac'),
	   ('222', 'Otras especialidades artisticas (especificar)', 'LD', '21', 'ac'),
	   ('223', 'Sociologia cultural', 'LD', '22', 'ac'),
	   ('224', 'Sociología experimental', 'LD', '22', 'ac'),
	   ('225', 'Sociologia general', 'LD', '22', 'ac'),
	   ('226', 'Problemas internacionale', 'LD', '22', 'ac'),
	   ('227', 'Sociologia matemática', 'LD', '22', 'ac'),
	   ('228', 'Sociologia del trabajo', 'LD', '22', 'ac'),
	   ('229', 'Cambio y desarrollo social', 'LD', '22', 'ac'),
	   ('230', 'Comunicaciones sociales', 'LD', '22', 'ac'),
	   ('231', 'Grupos sociales', 'LD', '22', 'ac'),
	   ('232', 'Problemas sociales', 'LD', '22', 'ac'),
	   ('233', 'Sociología de los asentamientos humanos', 'LD', '22', 'ac'),
	   ('234', 'Otras especialidades sociológicas (especificar)', 'LD', '22', 'ac'),
	   ('235', 'Etica clasica', 'LD', '23', 'ac'),
	   ('236', 'Etica de individuos', 'LD', '23', 'ac'),
	   ('237', 'Etica de grupo', 'LD', '23', 'ac'),
	   ('238', 'La ética en perspeciva (especificar)', 'LD', '23', 'ac'),
	   ('239', 'Otras especialidades relacionadas con la ética', 'LD', '23', 'ac'),
	   ('240', 'Filosofía del conocimiento', 'LD', '24', 'ac'),
	   ('241', 'Antropología filosófica', 'LD', '24', 'ac'),
	   ('242', 'Filosofía general', 'LD', '24', 'ac'),
	   ('243', 'Sistemas filosóficos', 'LD', '24', 'ac'),
	   ('244', 'Filosofía de la ciencia', 'LD', '24', 'ac'),
	   ('245', 'Filosofía de la naturaleza', 'LD', '24', 'ac'),
	   ('246', 'Filosofía social', 'LD', '24', 'ac'),
	   ('247', 'Doctrinas filosóficas', 'LD', '24', 'ac'),
	   ('248', 'Otras especialidades filosóficas (especificar)', 'LD', '24', 'ac');

